- name: Setup arch-based workstation
  hosts: localhost
  connection: local
  vars:
    packages:
      - fwupd
      - udisks2
      - vim
      - ansible
      - networkmanager
      - networkmanager-openconnect
      - network-manager-applet
      - xorg-server
      - xorg-xinit
      - acpi_call # TODO: for Lenovos
      - bc
      - mesa
      - ttf-jetbrains-mono
      - zip
      - unzip
      - git
      - openssh
      - nfs-utils
      - nftables
      - firefox
      - unclutter
      - man-db
      - stow
      - flameshot
      - dunst
      - nnn
      - fish
      - ripgrep
      - rclone
      - go
      - go-tools
      - rustup
      - rust-analyzer
      - typescript
      - dotnet-runtime
      - dotnet-sdk
      - rclone
      - rsync
      - rofi
      - zathura
      - zathura-pdf-mupdf
      - chromium
      - bat
      - conky
      - feh
      - exfat-utils
      - fzf
      - nodejs
      - openconnect
      - pulsemixer
      - pulseaudio
      - pulseaudio-alsa
      - samba
      - smbclient
      - sxiv
      - tldr
      - trayer
      - earlyoom
      - ttf-dejavu
      - gnome-keyring
      - screenfetch
      - autorandr
      - pandoc
      - reflector
      - python-pip
      - nmap
      - libqalculate
      - w3m
      - ncdu
      - croc
      - spotifyd
      - docker
      - ruby
      - ruby-irb
      - tree
      - xplr
      - xclip
      - ccache
      - neovim
      - jedi-language-server
      - typescript-language-server
      - lua-language-server
      - fd
      - eza
      - git-delta
      - broot
      - duf
      - tailscale
      - obsidian
      - deno
    aur_packages:
      - nerd-fonts-jetbrains-mono
      - gotop
      - slack-desktop
      - jetbrains-toolbox
      - yay
      - networkmanager-dmenu-git
      - rofi-dmenu
      - i3lock-color
      - spotify-tui

  tasks:
    - name: Check if AMD or Intel
      command: grep -q AMD /proc/cpuinfo
      ignore_errors: true
      changed_when: false
      register: is_amd

    - name: install AMD-specific packages
      when: is_amd
      community.general.pacman:
        state: present
        name:
          - xf86-video-amdgpu

    - name: Install general packages
      become: yes
      community.general.pacman:
        state: present
        name: "{{ packages }}"
            
    - name: Laptop-specific tasks
      tags: ['always', 'laptop']
      become: yes
      block:
        - name: install laptop-specific packages
          community.general.pacman:
            state: present
            name:
              - tlp
              - acpilight

        - name: Enable laptop-specific systemd units
          systemd:
            enabled: yes
            state: started
            name: "{{ item }}"
          loop:
            - tlp

        - name: Copy touchpad X11 conf file
          copy:
            src: "{{ playbook_dir }}/files/30-touchpad.conf"
            dest: /etc/X11/xorg.conf.d/30-touchpad.conf

    - name: Copy amdgpu X11 conf file
      become: yes
      when: is_amd
      copy:
        src: "{{ playbook_dir }}/files/20-amdgpu.conf"
        dest: /etc/X11/xorg.conf.d/20-amdgpu.conf

    - name: Enable systemd units
      become: yes
      systemd:
        enabled: yes
        state: started
        name: "{{ item }}"
      loop:
        - NetworkManager
        - systemd-timesyncd
        - nftables
        - earlyoom
        - sshd
        - reflector.timer
        - spotifyd
        - docker
        - fstrim
        - tailscaled

    - name: Configure reflector
      become: yes
      lineinfile:
        path: /etc/xdg/reflector/reflector.conf
        regexp: '^# --country'
        line: --country US

    - name: Enable YAML-based Ansible stdout
      become: yes
      lineinfile:
        path: /etc/ansible/ansible.cfg
        regexp: '^#stdout_callback = yaml'
        line: stdout_callback = yaml

    - name: Create user
      become: yes
      user:
        name: bhutch
        state: present
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        shell: /usr/bin/fish

    - name: Configure makepkg processor count
      become: yes
      lineinfile:
        path: /etc/makepkg.conf
        regexp: '^#MAKEFLAGS='
        line: MAKEFLAGS="-j{{ ansible_facts['processor_vcpus']}}"

    - name: Enable colored pacman output
      become: yes
      lineinfile:
        path: /etc/pacman.conf
        regexp: '^#Color'
        line: Color

    - name: Enable parallel pacman downloads
      become: yes
      lineinfile:
        path: /etc/pacman.conf
        regexp: '^#ParallelDownloads'
        line: ParallelDownloads = 5

    - name: Gather Git Repos
      set_fact:
        git_repos:
          - {dest: ~/scripts, repo: git@github.com:bhutch29/scripts.git}
          - {dest: ~/dotfiles, repo: git@github.com:bhutch29/dotfiles.git}
          - {dest: ~/org, repo: git@github.com:bhutch29/org.git}
          - {dest: ~/obsidian, repo: git@github.com:bhutch29/obsidian.git}

            # TODO: replace with yay
    - name: Gather AUR Repos
      set_fact:
        git_repos: "{{ git_repos + [{'dest': '~/pkgbuilds/' + item, 'repo': 'https://aur.archlinux.org/' + item + '.git'}] }}"
      loop: "{{ aur_packages }}"

    - name: Clone git repositories
      include_tasks: git_clone_idempotent.yml
      loop: "{{ git_repos }}"

    - name: Run Gnu Stow
      command:
        chdir: ~/dotfiles
        cmd: stow {{ item }}     
        creates: ~/.conkyrc
      loop:
        - misc

