- name: Setup Docker
  hosts: dockerServer
  remote_user: root
  gather_facts: False

  tasks:
    - name: Install packages
      community.general.apk:
        name: docker,docker-compose
        state: present
        update_cache: true

    - name: Enable service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: files/{{composeFile}}
        dest: /root/docker-compose.yml

    - name: Make sure supporting files dir exists
      file:
        path: "{{ item.dest | dirname }}"
        state: directory
      when: supportingFiles is defined
      loop: "{{supportingFiles}}"

    - name: Copy supporting files
      ansible.builtin.copy:
        src: files/{{item.src}}
        dest: "{{item.dest}}"
      when: supportingFiles is defined
      loop: "{{supportingFiles}}"

    - name: "Docker compose pull"
      command:
        cmd: docker-compose pull

    - name: "Docker compose up"
      command:
        cmd: docker-compose up -d
