- name: Setup Docker
  hosts: dockerServer
  remote_user: root
  gather_facts: False

  tasks:
    - name: Install packages
      community.general.apk:
        name: docker,docker-compose
        state: present
        update_cache: true

    - name: Enable service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Copy docker-compose file
      ansible.builtin.copy:
        src: files/{{composeFile}}
        dest: /root/docker-compose.yml
        backup: yes

    - name: "Docker compose pull"
      command:
        cmd: docker-compose pull

    - name: "Docker compose up"
      command:
        cmd: docker-compose up -d
