- name: Setup Docker
  hosts: dockerServers
  remote_user: root
  gather_facts: False

  tasks:
    - name: Install packages
      community.general.apk:
        name: docker,docker-compose
        state: present
        update_cache: true

    - name: Enable service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    # - name: Copy docker-compose templates for each service
    #   ansible.builtin.template:
    #     src: files/docker_services/{{ item.project_name }}.yml.j2
    #     dest: /home/maintenance/docker_services/{{ item.project_name }}/docker-compose.yml
    #     backup: yes
    #   loop: "{{ docker_services }}"
    #
    # - name: "Update docker service image"
    #   command:
    #     chdir: /home/maintenance/docker_services/{{ item.project_name }}
    #     cmd: docker-compose pull
    #   loop: "{{ docker_services }}"
    # - name: "Start docker service"
    #   command:
    #     chdir: /home/maintenance/docker_services/{{ item.project_name }}
    #     cmd: docker-compose up -d
    #   loop: "{{ docker_services }}"
