servers:
  children:
    lxcServers:
    hardwareServers:

lxcServers:
  hosts:
    dockerhost:
      ip: 192.168.1.101
    tailnode:
      ip: 192.168.1.210
    media:
      ip: 192.168.1.202

hardwareServers:
  hosts:
    router:
      ip: 192.168.1.1
    proxmox1:
      ip: 192.168.1.97
    idrac.proxmox1:
      ip: 192.168.1.98
    pve:
      ip: 192.168.1.100
    rack0pi:
      ip: 192.168.1.196
    idrac.pve:
      ip: 192.168.1.197
    garagedoor:
      ip: 192.168.1.198
    nut:
      ip: 192.168.1.199

proxmox:
  hosts:
    192.168.1.100

alpineLxc:
  hosts:
    192.168.1.208

rpis:
  hosts:
    192.168.1.199: #nut
    192.168.1.196: #rack0Pi?
