proxmox:
  hosts:
    192.168.1.100:
  vars:
    containers:
      # TODO
      # - {name: dockerhost, id: 201, cores: 2, memory: 16000, swap: 1024, storage: 16}
      # - {name: media, id: 202, cores: 2, memory: 8192, swap: 1024, storage: 16}
      # - {name: tailnode, id: 210, cores: 1, memory: 2048, swap: 512, storage: 16}
      - {name: test, id: 208, cores: 1, memory: 2048, swap: 512, storage: 16}
      - {name: test2, id: 209, cores: 1, memory: 2048, swap: 512, storage: 76}

alpineLxc:
  hosts:
    192.168.1.208: # TODO
    192.168.1.209: # TODO
  vars:
    ansible_python_interpreter: auto_silent
    tailscale_args: "--ssh"

exitNode:
  hosts:
    192.168.1.208: # TODO
  vars:
    tailscale_args: "--ssh --advertise-exit-node --advertise-routes=192.168.1.0/24"


dockerServers:
  hosts:
    192.168.1.209: # TODO
  vars:
    ansible_python_interpreter: auto_silent






servers:
  children:
    lxcServers:
    hardwareServers:

lxcServers:
  hosts:
    dockerhost:
      ip: 192.168.1.101
    tailnode:
      ip: 192.168.1.210
    media:
      ip: 192.168.1.202

hardwareServers:
  hosts:
    router:
      ip: 192.168.1.1
    pve:
      ip: 192.168.1.100
    rack0pi:
      ip: 192.168.1.196
    garagedoor:
      ip: 192.168.1.198
    nut:
      ip: 192.168.1.199

rpis:
  hosts:
    192.168.1.199: #nut
    192.168.1.196: #rack0Pi?
