servers:
  children:
    dockerServers:
    lxcServers:
    vmServers:
    hardwareServers:

dockerServers:
  hosts:
    nextcloud:
      ip: 192.168.1.201

lxcServers:
  hosts:
    gitlab:
      ip: 192.168.1.101
    pihole:
      ip: 192.168.1.102
    unifi:
      ip: 192.168.1.104
    unifivideo:
      ip: 192.168.1.106

vmServers:
  hosts:
    dockerhost:
      ip: 192.168.1.201

hardwareServers:
  hosts:
    router:
      ip: 192.168.1.1
    proxmox1:
      ip: 192.168.1.97
    idrac.proxmox1:
      ip: 192.168.1.98
    pve:
      ip: 192.168.1.100
    rack0pi:
      ip: 192.168.1.196
    idrac.pve:
      ip: 192.168.1.197
    garagedoor:
      ip: 192.168.1.198
    nut:
      ip: 192.168.1.199

rpis:
  hosts:
    192.168.1.199: #nut
    192.168.1.198: #garagedoor
    192.168.1.196: #rack0Pi?

ubuntu:
  hosts:
    192.168.1.102: #pihole
    192.168.1.103: #aptcacher
    192.168.1.104: #unifi
    192.168.1.201: #dockerhost
    192.168.1.106: #unifivideo
    192.168.1.110: #mqttclient
    192.168.1.111: #workout

ipaServers:
  hosts:
    192.168.1.203 #ipa
