proxmox:
  hosts:
    192.168.1.100:
  vars:
    containers:
      # - {name: dockerhost, id: 201, cores: 2, memory: 8192, swap: 1024, storage: 16}
      - {name: media, id: 202, cores: 8, memory: 16384, swap: 2048, storage: 16}
      - {name: tailnode, id: 210, cores: 1, memory: 2048, swap: 512, storage: 16}

alpineLxc:
  hosts:
    # 192.168.1.201:
    192.168.1.202:
    192.168.1.210:
  vars:
    ansible_python_interpreter: auto_silent
    tailscale_args: "--ssh"

exitNode:
  hosts:
    192.168.1.210:
  vars:
    tailscale_args: "--ssh --advertise-exit-node --advertise-routes=192.168.1.0/24"

mediaServer: # TODO: split generic docker setup
  hosts:
    192.168.1.202:
  vars:
    ansible_python_interpreter: auto_silent






servers:
  children:
    hardwareServers:

hardwareServers:
  hosts:
    router:
      ip: 192.168.1.1
    pve:
      ip: 192.168.1.100
    rack0pi:
      ip: 192.168.1.196
    garagedoor:
      ip: 192.168.1.198
    nut:
      ip: 192.168.1.199

rpis:
  hosts:
    192.168.1.199: #nut
    192.168.1.196: #rack0Pi?
