proxmox:
  hosts:
    192.168.1.100:
  vars:
    containers:
      - {name: dockerhost, id: 201, cores: 2, memory: 8192, swap: 1024, storage: 16, template: alpine}
      - {name: media, id: 202, cores: 8, memory: 16384, swap: 2048, storage: 16, template: alpine}
      - {name: historian, id: 203, cores: 1, memory: 2048, swap: 512, storage: 16, template: debian}
      # - {name: workspace, id: 204, cores: 4, memory: 16384, swap: 512, storage: 32, template: arch}
      - {name: tailnode, id: 210, cores: 1, memory: 2048, swap: 512, storage: 16, template: alpine}

alpineLxc:
  hosts:
    192.168.1.201:
    192.168.1.202:
    192.168.1.210:

debianLxc:
  hosts:
    192.168.1.203:

# TODO: arch containers aren't working, can't install or upgrade
# archLxc:
#   hosts:
#     192.168.1.204:

tailscaleLxc:
  hosts:
    192.168.1.201:
    192.168.1.202:
    192.168.1.203:
    192.168.1.204:
    192.168.1.210:
  vars:
    ansible_python_interpreter: auto_silent
    tailscale_args: "--ssh"

exitNode:
  hosts:
    192.168.1.210:
  vars:
    tailscale_args: "--ssh --advertise-exit-node --advertise-routes=192.168.1.0/24"

dockerServer:
  hosts:
    192.168.1.201:
      composeFile: 'docker-compose.yml'
    192.168.1.202:
      composeFile: 'docker-compose.media.yml'
  vars:
    ansible_python_interpreter: auto_silent

historian:
  hosts:
    192.168.1.203:





servers:
  children:
    hardwareServers:

hardwareServers:
  hosts:
    router:
      ip: 192.168.1.1
    pve:
      ip: 192.168.1.100
    rack0pi:
      ip: 192.168.1.196
    garagedoor:
      ip: 192.168.1.198
    nut:
      ip: 192.168.1.199

rpis:
  hosts:
    192.168.1.199: #nut
    192.168.1.196: #rack0Pi?
