- name: Setup Tailscale
  hosts: alpineLxc
  remote_user: root
  gather_facts: False

  tasks:
    - name: Install packages
      community.general.apk:
        name: tailscale
        state: present
        update_cache: true

    - name: Enable service
      ansible.builtin.service:
        name: tailscale
        state: started
        enabled: yes
