- name: Install Tailscale
  hosts: alpineLxc
  remote_user: root
  gather_facts: False

  tasks:
    - name: Install packages (Alpine)
      community.general.apk:
        name: tailscale
        state: present
        update_cache: true
