- name: Configure FreeIPA DNS records
  hosts: ipa-servers

  vars:
    domain: in.bhutch.org
    ssl_cert_path: "/etc/pki/tls/certs"
    ssl_key_path: "/etc/pki/tls/private"

  tasks:
    - name: Create IPA DNS records
      ipa_dnsrecord:
        ipa_host: "ipa.{{ domain }}"
        ipa_pass: Brzbat29
        state: present
        zone_name: "{{ domain }}"
        record_name: "{{ item }}"
        record_value: "{{ hostvars[item]['ip'] }}"
        record_type: "A"
        record_ttl: 300
      with_items: "{{ groups['servers'] }}"

    - name: Create IPA Host Entries
      ipa_host:
        name: "{{ item }}.{{ domain }}"
        ipa_host: "ipa.{{ domain }}"
        ipa_pass: Brzbat29
      with_items: "{{ groups['servers'] }}"

    - name: Create IPA HTTP Services and Delegate to IPA Server
      ipa_service:
        name: "HTTP/{{ item }}.{{ domain }}"
        hosts:
          - "{{ item }}.{{ domain }}"
          - "ipa.{{ domain }}"
        ipa_host: "ipa.{{ domain }}"
        ipa_pass: Brzbat29
        state: present
      with_items: "{{ groups['servers'] }}"

    - name: Request SSL Certificates
      command: ipa-getcert request \
        -r \
        -f '{{ ssl_cert_path }}/{{ item }}.{{ domain }}.crt' \
        -k '{{ ssl_key_path }}/{{ item }}.{{ domain }}.key' \
        -N 'CN={{ item }}.{{ domain }}' \
        -D '{{ item }}.{{ domain }}' \
        -K 'HTTP/{{ item }}.{{ domain }}'
      args:
        creates: '{{ ssl_cert_path }}/{{ item }}.{{ domain }}.crt'
      with_items: "{{ groups['servers'] }}"

    # - name: Copy SSL Certificates
    #   # TODO: how to decide where to copy these to? Nginx reverse proxy? File on the host itself?
    #   hosts: '{{ item.cert_target_host }}'
    #   synchronize: 'src={{ ssl_cert_path }}/{{ item.name }}.{{ domain }}.crt dest={{ item.cert_target_folder }}'
    #   delegate_to: ipa
