- name: Create IPA hosts, services, dns records, and ssl certificates
  hosts: ipa-servers

  vars:
    domain: in.bhutch.org
    ssl_cert_path: "/etc/pki/tls/certs"
    ssl_key_path: "/etc/pki/tls/private"

  tasks:
    - name: Create IPA DNS records
      ipa_dnsrecord:
        ipa_host: "ipa.{{ domain }}"
        ipa_pass: Brzbat29
        state: present
        zone_name: "{{ domain }}"
        record_name: "{{ item }}"
        record_value: "{{ hostvars[item]['ip'] }}"
        record_type: "A"
        record_ttl: 300
      with_items: "{{ groups['servers'] }}"

    - name: Create IPA Host Entries
      ipa_host:
        name: "{{ item }}.{{ domain }}"
        ipa_host: "ipa.{{ domain }}"
        ipa_pass: Brzbat29
      with_items: "{{ groups['servers'] }}"

    - name: Create IPA HTTP Services and Delegate to IPA Server
      ipa_service:
        name: "HTTP/{{ item }}.{{ domain }}"
        hosts:
          - "{{ item }}.{{ domain }}"
          - "ipa.{{ domain }}"
        ipa_host: "ipa.{{ domain }}"
        ipa_pass: Brzbat29
        state: present
      with_items: "{{ groups['servers'] }}"

    - name: Request SSL Certificates
      command: ipa-getcert request \
        -r \
        -f '{{ ssl_cert_path }}/{{ item }}.{{ domain }}.crt' \
        -k '{{ ssl_key_path }}/{{ item }}.{{ domain }}.key' \
        -N 'CN={{ item }}.{{ domain }}' \
        -D '{{ item }}.{{ domain }}' \
        -K 'HTTP/{{ item }}.{{ domain }}'
      args:
        creates: '{{ ssl_cert_path }}/{{ item }}.{{ domain }}.crt'
      with_items: "{{ groups['servers'] }}"

    - name: Fetch SSL Certificates
      fetch:
        src: "{{ ssl_cert_path }}/{{ item }}.{{ domain }}.crt"
        dest: "/etc/ansible/temp/certs/"
        flat: yes
      with_items: "{{ groups['servers'] }}"

    - name: Fetch SSL Keys
      fetch:
        src: "{{ ssl_key_path }}/{{ item }}.{{ domain }}.key"
        dest: "/etc/ansible/temp/certs/"
        flat: yes
      with_items: "{{ groups['servers'] }}"

- name: Distribute SSL Keys/Certs
  hosts: docker-servers
  gather_facts: no

  vars:
    docker_cert_path: "/var/lib/docker/volumes/proxy_certs/_data"
    domain: in.bhutch.org

  tasks:
    - name: Copy SSL Certificates - Docker
      copy:
        src: "/etc/ansible/temp/certs/{{ inventory_hostname }}.{{ domain }}.crt"
        dest: "{{ docker_cert_path }}/{{ inventory_hostname }}.{{ domain }}.crt"

    - name: Copy SSL Keys - Docker
      copy:
        src: "/etc/ansible/temp/certs/{{ inventory_hostname }}.{{ domain }}.key"
        dest: "{{ docker_cert_path }}/{{ inventory_hostname }}.{{ domain }}.key"
