- hosts: 127.0.0.1
  connection: local

  vars:
     pool: tank
     mountsize: 8
     template: iso:ubuntu-16.04-standard_16.04-1_amd64.tar.gz
     cores: 1
     memory: 512
     onboot: no
     publickey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWfht6OxrIGhUeurb+SmFBycL7plnmIDvcLiM6jf6YiasXlEg7/RaoOfaTaZGOWt0SikSIyU4dB8HkBKnoJDH7NfYavDR7R9fayE0AT9zY+XTjIoXOa+SpxqfV9Um2d9wPhHf8hLPmU8tmdKP34aQqmV8V7R32fzb0nRPYOm++Zz4Uoz3Y9PWmG80XEPHb0Z+FdhIdyS/9ZDmJvXcvKXkrQu9LrobpzcXV1KtWeTmLaYDbLk1akE+D5wRAPgHQalMrXE/h232UPniiq1FIQXelgRZHzu8dkmRl5xv+BiYft0uop3ouoz3q0CZ/dSneJsNgSVcde0qswxKzAg2soMD/ root@pve

  tasks:
     - name: create zfs file system
       zfs:
          name: "{{pool}}/appdata/{{containername | mandatory}}"
          state: present
     - name: get ZFS storage list from PVE
       command: pvesm zfsscan
       register: proxmox_zfs_storage
     - name: add file system to PVE
       shell: pvesm add zfs {{containername | mandatory}} -pool {{pool}}/appdata/{{containername | mandatory}}
       when: proxmox_zfs_storage.stdout | search('{{pool}}/appdata/{{containername | mandatory}}')
     - name: create Ubuntu 16.04 LXC container in Proxmox
       proxmox:
          vmid: {{id | mandatory}}
          node: pve
          api_user: root@pam
          api_password: Brzbat29
          api_host: {{containername | mandatory}}
          password: Brzbat29
          hostname: {{containername | mandatory}}
          ostemplate: {{template}}
          netif: '{"net0":"name=eno1,gw=192.168.1.1,ip=192.168.1.{{id}}/24,bridge=vmbr0}'
          mounts: '{"mp0":"{{containername | mandatory}}:{{mountsize}},mp=/mnt/appdata"}'
          cores: {{cores}}
          memory: {{memory}}
          state: present
          pubkey: {{publickey}}
          onboot: {{onboot}} 
     - name: start container
       proxmox:
          vmid: {{id}}
          api_user: root@pam
          api_password: Brzbat29
          api_host: {{containername | mandatory}}
          state: started
