- hosts: 127.0.0.1
  connection: local

  vars:
     pool: tank

  tasks:
     - name: create zfs file system
       zfs:
          name: "{{pool}}/appdata/{{containername | mandatory}}"
          state: present
#     - name: create LXC container in Proxmox
#       proxmox:
#          vmid:
