- name: Setup arch-based workstation
  gather_facts: yes
  hosts: localhost
  connection: local
  vars:
    packages:
      - fwupd
      - udisks2
      - vim
      - ansible
      - networkmanager
      - networkmanager-openconnect
      - network-manager-applet
      - xorg-server
      - xorg-xinit
      - acpi_call # TODO: for Lenovos
      - bc
      - mesa
      - ttf-jetbrains-mono
      - git
      - openssh
      - nfs-utils
      - nftables
      - firefox
      - unclutter
      - man-db
      - stow
      - flameshot
      - dunst
      - nnn
      - fish
      - ripgrep
      - rclone
      - go
      - go-tools
      - rustup
      - typescript
      - dotnet-runtime
      - dotnet-sdk
      - rclone
      - rsync
      - rofi
      - zathura
      - zathura-pdf-mupdf
      - chromium
      - bat
      - conky
      - feh
      - exfat-utils
      - fzf
      - nodejs
      - openconnect
      - pulsemixer
      - pulseaudio
      - pulseaudio-alsa
      - samba
      - smbclient
      - sxiv
      - tldr
      - trayer
      - earlyoom
      - ttf-dejavu
      - gnome-keyring
      - emacs
      - screenfetch

  tasks:
    - name: Check if AMD or Intel
      command: grep -q AMD /proc/cpuinfo
      ignore_errors: true
      changed_when: false
      register: is_amd

    - name: install AMD-specific packages
      when: is_amd
      community.general.pacman:
        state: present
        name:
          - xf86-video-amdgpu

    - name: Install general packages
      become: yes
      community.general.pacman:
        state: present
        name: "{{ packages }}"
            
    - name: Laptop-specific tasks
      tags: ['always', 'laptop']
      block:
        - name: install laptop-specific packages
          community.general.pacman:
            state: present
            name:
              - tlp
              - acpilight

        - name: Enable laptop-specific systemd units
          become: yes
          systemd:
            enabled: yes
            state: started
            name: "{{ item }}"
          loop:
            - tlp

        - name: Copy touchpad X11 conf file
          become: yes
          copy:
            src: "{{ playbook_dir }}/files/30-touchpad.conf"
            dest: /etc/X11/xorg.conf.d/30-touchpad.conf

    - name: Copy amdgpu X11 conf file
      become: yes
      when: is_amd
      copy:
        src: "{{ playbook_dir }}/files/20-amdgpu.conf"
        dest: /etc/X11/xorg.conf.d/20-amdgpu.conf

    - name: Enable systemd units
      become: yes
      systemd:
        enabled: yes
        state: started
        name: "{{ item }}"
      loop:
        - NetworkManager
        - systemd-timesyncd
        - nftables
        - earlyoom
        - sshd

    - name: Create user
      become: yes
      user:
        name: bhutch
        state: present
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        shell: /usr/bin/fish

    - name: Configure makepkg processor count
      become: yes
      lineinfile:
        path: /etc/makepkg.conf
        regexp: '^#MAKEFLAGS='
        line: MAKEFLAGS="-j{{ ansible_facts['processor_vcpus']}}"

    - name: Enable colored pacman output
      become: yes
      lineinfile:
        path: /etc/makepkg.conf
        regexp: '^#Color'
        line: Color

    - name: Setup git email
      community.general.git_config:
        name: user.email
        value: inukage0029@gmail.com
        scope: global

    - name: Setup git username
      community.general.git_config:
        name: user.name
        value: Bradley Hutchinson
        scope: global

    - name: Setup git pull method
      community.general.git_config:
        name: pull.rebase
        value: "false"
        scope: global

    - name: Clone git repositories
      tags: ['never', 'git']
      block:
        - name: Clone scripts repo
          git:
            dest: ~/scripts
            repo: git@github.com:bhutch29/scripts.git
            update: no
    
        - name: Clone dotfiles repo
          git:
            dest: ~/dotfiles
            repo: git@github.com:bhutch29/dotfiles.git
            update: no

        - name: Clone org repo
          git:
            dest: ~/org
            repo: git@github.com:bhutch29/org.git
            update: no

        - name: Clone spacemacs
          git:
            dest: ~/.emacs.d
            repo: git@github.com:bhutch29/org.git
            update: no

        - name: Clone intellimacs repo
          git:
            dest: ~/.intellimacs
            repo: https://github.com/MarcoIeni/intellimacs
            update: no
    
        - name: Clone intellimacs repo
          git:
            dest: ~/.emacs.d
            repo: https://github.com/syl20bnr/spacemacs
            update: no

        - name: Clone AUR repos
          git:
            dest: ~/pkgbuilds
            repo: https://aur.archlinux.org/{{ item }}.git
            update: no
          loop:
            - nerd-fonts-jetbrains-mono
            - gcc8
            - gotop
            - angular-cli
            - conan
            - slack-desktop
            - jetbrains-toolbox
            - yay
            - networkmanager-dmenu-git
            - rofi-dmenu
            - i3lock-color

    - name: Run Gnu Stow
      command:
        chdir: ~/dotfiles
        cmd: stow {{ item }}     
        creates: ~/.conkyrc
      loop:
        - vim
        - misc

