- name: Setup Proxmox
  hosts: proxmox
  remote_user: root
  gather_facts: False
  vars:
    containers:
      - {name: dockerhost, id: 201, cores: 2, memory: 16000, swap: 1024, storage: 16G}
      # - {name: media, id: 202, cores: 2, memory: 8192, swap: 1024, storage: 16G}
      - {name: tailnode, id: 210, cores: 1, memory: 2048, swap: 512, storage: 16G}

  tasks:
    # - name: Create ZFS file system, add to PVE
    #   when: item.TODO
    #   include_tasks: zfs.yml
    #   loop: {{containers}}

    - name: Create LXC container
      community.general.proxmox:
        vmid: "{{item.id}}"
        node: pve
        api_user: root@pam
        api_password: "{{api_password}}"
        api_host: pve
        password: "{{container_password}}"
        hostname: "{{item.name}}"
        ostemplate: 'local:vztmpl/alpine-3.18-default_20230607_amd64.tar.xz'
        netif: '{"net0":"name=eth0,gw=192.168.1.1,ip=192.168.1.{{item.id}}/24,bridge=vmbr0"}'
        disk: 16
        mounts: '{"mp0":"/mnt/pve/share,mp=/mnt/share"}'
        state: present
        cores: "{{item.cores}}"
        memory: "{{item.memory}}"
        swap: "{{item.swap}}"
        onboot: yes
        unprivileged: yes
        storage: vmstorage
      loop: "{{containers}}"
        

    - name: Start LXC container
      community.general.proxmox:
        vmid: "{{item.id}}"
        node: pve
        api_user: root@pam
        api_password: "{{api_password}}"
        api_host: pve
        state: started
      loop: "{{containers}}"
