version: '3.7'

services:
  ts-homeassistant:
    image: tailscale/tailscale:latest
    container_name: ts-homeassistant
    hostname: homeassistant
    ports:
      - "8123:8123"
    environment:
      - TS_AUTHKEY={{tailscale_authkey_homeassistant}}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/tailscale-serve-homeassistant.json
    volumes:
      - /root/ts-homeassistant/state:/var/lib/tailscale
      - /root/ts-homeassistant/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    network_mode: service:ts-homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /mnt/appconfig/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    depends_on:
      - ts-homeassistant

  ts-gitea:
    image: tailscale/tailscale:latest
    container_name: ts-gitea
    hostname: gitea
    ports:
      - "3000:3000"
    environment:
      - TS_AUTHKEY={{tailscale_authkey_homeassistant}}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/tailscale-serve-gitea.json
    volumes:
      - /root/ts-gitea/state:/var/lib/tailscale
      - /root/ts-gitea/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  gitea:
    image: gitea/gitea:latest-rootless
    container_name: gitea
    environment:
      - USER_UID=0
      - USER_GID=0
    restart: always
    network_mode: service:ts-gitea
    volumes:
      - /mnt/appconfig/gitea/data:/var/lib/gitea
      - /mnt/appconfig/gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  
  # historian:
  #   container_name: historian
  #   restart: always
  #   image: denoland/deno:debian
  #   # TODO: ports
  #   volumes:
  #     - /root:/app
  #   command: run --allow-all --unstable-kv --unstable-cron /app/historian.ts
