version: "2"
services:
  sabnzbd:
    image: "linuxserver/sabnzbd"
    container_name: "sabnzbd"
    volumes:
      - /mnt/appconfig/sabnzbd:/config
      - /mnt/share/downloads/completed:/downloads
      - /mnt/share/downloads/incomplete:/incomplete-downloads
      - /root/certs:/certs
    ports:
        - "8002:8080"
    restart: always
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/PDT

  radarr:
    image: "linuxserver/radarr"
    container_name: "radarr"
    volumes:
      - /mnt/appconfig/radarr:/config
      - /mnt/share/downloads/completed:/downloads
      - /mnt/share/media/movies:/movies
      - "/etc/localtime:/etc/localtime:ro"
      - /root/certs:/certs
    ports:
      - "7878:7878"
    restart: always
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/PDT

  sonarr:
    image: "linuxserver/sonarr"
    container_name: "sonarr"
    volumes:
      - /mnt/appconfig/sonarr:/config
      - /mnt/share/downloads/completed:/downloads
      - /mnt/share/media/tvshows:/tv
      - "/etc/localtime:/etc/localtime:ro"
      - /root/certs:/certs
    ports:
        - "8004:8989"
    restart: always
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/PDT

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/PDT
      - JELLYFIN_PublishedServerUrl=192.168.1.209
    volumes:
      - /mnt/appconfig/jellyfin_config:/config
      - /mnt/share/media/tvshows:/data/tvshows
      - /mnt/share/media/movies:/data/movies
    ports:
      - 8096:8096
      # - 8920:8920 #optional, https web gui
      - 7359:7359/udp #optional, local network service discovery
      - 1900:1900/udp #optional, service discovery used by DNLA and clients
    restart: always

  # plexms:
  #   container_name: plexms
  #   restart: always
  #   image: plexinc/pms-docker
  #   volumes:
  #     - /root/plexms:/config
  #     - /mnt/share/downloads/plex_tmp:/transcode
  #     - /mnt/share/media:/media
  #     - /root/certs:/certs
  #   network_mode: host
  #   environment:
  #     - HOSTNAME="Docker Plex"
  #     - PLEX_CLAIM="claim-XrKke5jurEYizZxdhGFa"
  #     - ADVERTISE_IP="http://192.168.1.201:32400/"
