# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 38.4582
  longitude: -122.5937
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 240
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

# ecobee:
#   api_key: 8RfMiUAoqafDxyDqM9oS6MSTbRsRzSyR

# camera:
#   - platform: uvc
#     nvr: 192.168.1.106
#     key: 0q16r2XItVLgApOPef4gyp636BIaIX4O
#     password: Brzbat29

  # - platform: speedtest
  #   monitored_conditions:
  #     - ping
  #     - download
  #     - upload

#  - platform: sabnzbd
#  host: 192.168.1.201
#  port: 8002
#  api_key: a53cc4c425c04d9dff565a58d4966bba
#  monitored_variables:
#    - 'current_status'
#    - 'speed'
#    - 'queue_size'
#    - 'queue_remaining'
#    - 'disk_size'
#    - 'disk_free'
#    - 'queue_count'
